"""add verify user

Revision ID: 9fc0fc6a1ce7
Revises: bb62be3e9c9e
Create Date: 2024-06-06 13:11:21.675846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fc0fc6a1ce7'
down_revision: Union[str, None] = 'bb62be3e9c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('admin', 'moderator', 'user', name='role'), autoincrement=False, nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
